### PR TITLE
refactor!: update project sructure and dependencies

### PR DESCRIPTION
**Pull request by ngort01**
This updates the project structure and tooling and also now uses @rjsf/core instead of react-jsonschema-form. So the packege can be used like all the other themenig [packages ](https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages).

Additional changes:
- adds MultiSchemaField to support nested schemas
- allow  basic theming through form context (primary color, focus color, text color and so on)
- minor fixes and improvements

### CODE REVIEW

**Review by zhigang1992 — APPROVED** [review]
This is great!

👍

**Comment by zhigang1992** [comment]
@ngort01 are you able to get example app to work?

I'm experiencing crash on launch and missing font of Roboto when using iOS simulator?

We should properly not be using Roboto since it might be available in the app bundle?

**Comment by ngort01** [comment]
@zhigang1992 I'll remove the Roboto font.
The example works for me on Windows + Android. 
I don't have a Mac here to try it on on iOS. Does it scrash because of the missing Roboto Font or is this just an additional error?

**Comment by zhigang1992** [comment]
@ngort01 there were additional errors in the Xcode. I can look more into that a bit later.

**Comment by zhigang1992** [comment]
Screen Shot 2020-07-14 at 4 51 24 PM

This was the first one, I removed `FontFamily: ''`

And then

Screen Shot 2020-07-14 at 4 55 12 PM

Upgraded Flipper version solved that

And then

Screen Shot 2020-07-14 at 5 00 48 PM

It works

**Comment by ngort01** [comment]
@zhigang1992 cool!

There's still this open [issue](https://github.com/rjsf-team/react-jsonschema-form/issues/696). Maybe we can get this package there

**Comment by zhigang1992** [comment]
Ah right, I completely forget about that.

I not against moving it there. Just not have the time to craft a proper PR for it.

You can take on that if you have some time.

**Comment by ngort01** [comment]
Okay, maybe I'll find some time to do it

**Comment by firrae** [comment]
Any update on that issue? This might be exactly what I need for my application. While I'm fine using a separate package, getting it included in main somehow would be great overall.

**Pull request merged**
